"""init

Revision ID: 27033dc3891e
Revises: 
Create Date: 2024-10-01 04:03:19.639279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '27033dc3891e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('short_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publishing_house', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skills', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('bookinstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_book', sa.Integer(), nullable=False),
    sa.Column('id_reader', sa.Integer(), nullable=False),
    sa.Column('status_book', sa.Enum('New', 'Old', 'Lost', name='choicesbook'), nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['id_reader'], ['reader.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_book', sa.Integer(), nullable=False),
    sa.Column('offer_book', sa.Integer(), nullable=False),
    sa.Column('exchange_start', sa.DateTime(), nullable=False),
    sa.Column('exchange_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_book'], ['bookinstance.id'], ),
    sa.ForeignKeyConstraint(['request_book'], ['bookinstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchangehistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_book', sa.Integer(), nullable=False),
    sa.Column('offer_book', sa.Integer(), nullable=False),
    sa.Column('exchange_start', sa.DateTime(), nullable=False),
    sa.Column('exchange_end', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['offer_book'], ['bookinstance.id'], ),
    sa.ForeignKeyConstraint(['request_book'], ['bookinstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchangerequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_book', sa.Integer(), nullable=False),
    sa.Column('offer_book', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('exchange_start', sa.DateTime(), nullable=False),
    sa.Column('exchange_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Awaiting', 'Accepted', 'Denied', name='choices'), nullable=False),
    sa.ForeignKeyConstraint(['offer_book'], ['bookinstance.id'], ),
    sa.ForeignKeyConstraint(['request_book'], ['bookinstance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchangerequest')
    op.drop_table('exchangehistory')
    op.drop_table('exchange')
    op.drop_table('bookinstance')
    op.drop_table('reader')
    op.drop_table('book')
    # ### end Alembic commands ###
